### ISSUE TITLE
iPhone - DashWallet v.0.9 (incl IX) Crashing

### ISSUE THREAD

**Issue by skaht** [QuantumExplorer/dashwallet#12]
v8.8 crashed until I upgraded to v.0.9.  During the transition, the BIP 39 functionality to restore the keys worked fine.  v.0.9 worked for many months. Currently running iOS 9.3.2 (13F69). Any suggestions or should I wait for the JAXX release to do the BIP 39 restore. Unclear if JAXX is to support IX or PP.

**Comment by Raginglikeaboss** [comment]
I had attempted to use the BIP 39 restore functionality in JAXX via my Chrome extension, and it appears that they are incompatible with each other.

I believe this is because JAXX restoration from it's own seed restores all of the various cryptocurrency holdings.
