### ISSUE TITLE
Not properly scaled iPhone6

### ISSUE THREAD

**Issue by karek314** [QuantumExplorer/dashwallet#14]
Not properly scaled iPhone6/6Plus - wallet is not properly scaled to higher resolution, this issue has been already solved in breadwallet.

**Comment by karek314** [comment]
Why closed, appear that it's not fixed yet ?

**Comment by Raginglikeaboss** [comment]
It will not properly sync on my iPhone 5 LE nor my iPad Air 1 anymore either.

Why was this Issue 'closed?'
