### ISSUE TITLE
sync gets blocked at block 593977 (out of 598396)

### ISSUE THREAD

**Issue by octavflorescu** [QuantumExplorer/dashwallet#16]
Two days ago, the wallet stopped syncing above block 593977.
The version on which the wallet was first created was the one which reached the AppStore.
Have downloaded the repo and ran on two devices, both master and distribution branch.
Devices:
iPhone SE iOS 10.0.2
iPhone 5S iOS 9.3.5

**Comment by octavflorescu** [comment]
Solution: needed an update of difficulty

Add this line at the end of the checkpoints_array []

{ 603455, "00000000000068678e10028c0b5243a2a49c73cfd5869b64294af654d5b1bf8a", 1484340221, 0x1b00cdbdu }//dash

![screen shot 2017-01-13 at 23 17 17](https://cloud.githubusercontent.com/assets/15170320/21945991/03d4de22-d9e7-11e6-8f7e-fca89a1e8603.png)

**Comment by HashEngineering** [comment]
This solution doesn't make sense to me, except for new users (wallets created after block 593977).  How did it solve the problem?

**Comment by octavflorescu** [comment]
It was entering the condition:

// verify block difficulty if block is past last checkpoint
    if ((block.height > (checkpoint_array[CHECKPOINT_COUNT - 1].height + DGW_PAST_BLOCKS_MAX)) && ![block verifyDifficultyWithPreviousBlocks:self.blocks]) {

Thus, the method - (void)peer:(BRPeer *)peer relayedBlock:(BRMerkleBlock *)block was returning instead of continuing the update, 'marking' the peer as corrupted... Marking any connected peer as corrupted, due to the given if check.

Opinion: Checkpoints array (array containing some 'safe transactions' as chackpoints) should not be hard-coded inside the wallet.

**Comment by HashEngineering** [comment]
Was the original problem that verifyDifficultyWithPreviousBlocks returned FALSE (0) on  593977?

To me this solution skips past the problematic block because it only checks the difficulty after the last checkpoint.  This wallet could be unsecure for wallets with transactions before this block.

The reason why this interests me is because I am working on a different coin's fork of breadwallet for android which also uses the DarkGravityWave3 code.  I am having trouble with the difficulty calculation not being correct on some blocks.  I am using the code that came from the iOS version which may have been taken from the dashwallet.

**Comment by octavflorescu** [comment]
sorry for the delayed not-an-answer. Most probably, yes, that method is the problem. The darkTarget returned by darkGravityWaveTargetWithPreviousBlocks is a small number, resulting in
int32_t diff = (self.target & 0x00ffffffu) - darkGravityWaveTarget;
being higher than 2.

**Comment by mkinney** [comment]
Problem exists on a later block now:
relayed orphan block <8b275d29 88381bfa bf3fd3fd 1dea6e45 103bd828 76d4b9cd ff640000 00000000>, height 2147483647, previous <6e697834 1595932c 6a109901 d14b5f3c d42a0340 ea1c43d3 75560000 00000000>, last block is <9c5e16bc 8f2395ca 5c0085c3 83bfb14c 8bbafe88 102871df 798b0000 00000000>, height 604733

How do you determine the values of the line to be added to checkpoint_array?

**Comment by mkinney** [comment]
I guess you can just take the most recent block... because that works for me:

    { 603455, "00000000000068678e10028c0b5243a2a49c73cfd5869b64294af654d5b1bf8a", 1484340221, 0x1b00cdbdu },//dash
    { 619269, "00000000000098d48949524d7a447aeedc39ae1a2ad7b3fa602e92dee0cafcf8", 1486832689, 0x1b00ab99u }//dash

Woo hoo!

**Comment by QuantumExplorer** [comment]
new version will be out within 3 days and will fix this and many other problems.

**Comment by mkinney** [comment]
Great! Which branch? Need help testing? ;-)

**Comment by octavflorescu** [comment]
Great news 👍

**Comment by QuantumExplorer** [comment]
new branch is called "refresh", it fixes this bug.  It's currently in internal testing since today, should be an open beta soon.  Or you can download that branch and run it yourself through xcode.

**Comment by ZCApple** [comment]
I was developing a new coin purse based on the Dash wallet, basically the same thing, only modifying the parameters and calculation difficulty of the creation block, and adding two words in outputEnitty. But I need to comment out all the checkpoints. What should I do? Thank you very much!
