### ISSUE TITLE
Is Deployment Target Set Too High?

### ISSUE THREAD

**Issue by mishfit** [QuantumExplorer/dashwallet#24]
I'm trying to figure out why the deployment target is set for 10.3...wouldn't 9.1 do (it looks like it's mostly complaining about `safeAreaLayoutGuide`)?

**Comment by QuantumExplorer** [comment]
This was done intentionally.  Even though I'm using 1 feature from iOS 10, I wanted to limit the number of different iOS versions that we support so we don't have to do as much testing when we deploy a new version.  We used to get back some reports like where the app was acting weirdly on older iOS versions.

So why 10.3 and not 10.0 you might ask?  Same reason, I want people to be updated.  It limits the risk of something not working properly on an older iOS version.
