### ISSUE TITLE
Custom network

### ISSUE THREAD

**Issue by Infernoman** [QuantumExplorer/dashwallet#7]
Hi there, Looking for a bit of help getting a forked version of the dash breadwallet online. I'm having a few troubles after my client has connected, while it is trying to download blocks. My coin is also X11 so i was hoping i wouldnt have to make too many changes. the wallet is generating addresses correctly, and the checkpoints have been changed. It is also connecting to the peer correctly and even trying to download blocks. But it fails on the POW check. I ended up removing that since my coin is POS, and it fails saying the block timestamp is too far in the future. if this is commented out. it will send and receive block headers, 2000 at a time. then tries to send a second getheader request. but fails with "invalid block header"

**Comment by QuantumExplorer** [comment]
Every network is very different.  It took me about a month to understand how to connect to the dash network correctly.  It's too hard for me to help you without having a deep understanding of your coin. Dash using Dark Gravity Well, I'm not sure what your coin uses, but you definitively should include it to make sure the block is valid.  For block timestamps I don't know.  Invalid block headers I also don't know.

**Comment by Infernoman** [comment]
Would you consider working on it as a separate project if it is paid for?

**Comment by QuantumExplorer** [comment]
I guess... why not? I like working on crypto anyways and I have a few days free coming up.
Email me : quantumexplorer AT hotmail DOT com
With info and what your expectations are (basically what you want me to do) and then I'll send you my rates.
