### ISSUE TITLE
iOS: "import private key" issue?

### ISSUE THREAD

**Issue by skaht** [QuantumExplorer/dashwallet#8]
Liked the [instructions](https://dashpay.atlassian.net/wiki/display/DOC/Download+-+Install+-+Guide) enough to give them a test drive ;-)  

Generated a quick paper wallet using both [libbitcoin HD key synthesis: see examples #1 and #4](https://github.com/libbitcoin/libbitcoin/wiki/Altcoin-Version-Mappings#bx---wallet-commands) and [WalletGenerator.net "Wallet Details" tab](https://github.com/MichaelMure/WalletGenerator.net) offline.  Got compressed base64check encoded private and public keys to match between the two key synthesis mechanisms. Afterwards, used [shapeshift.io](https://shapeshift.io) to successfully load the paper wallet.

The issue is that for dashwallet v0.8.8, specifically commit 361713b801ecef30e23a8bb95247e8726d63c126. I'm not currently able to import the 52 character compressed WIF key that I used shapeshift.io to sweep funds into described above.

Is the "import private key" functionality fully working, or am I trying to import a private key that is in the wrong format?

**Comment by QuantumExplorer** [comment]
Could you make me another test private key (empty one)?  I'll check to see what's going on.

**Comment by skaht** [comment]
##### 1. BIP 44 synthesis of Dash WIF private key using the bitcoin-explorer [bx](https://github.com/libbitcoin/libbitcoin-explorer/) command line (commit 2ccfe525a63907f3b45fd1a48033e8b08436799d):

*% echo 'This brain wallet is a joke, needs lots of salt and peppering.' | bx base16-encode | bx sha256 | bx hd-new | bx hd-private -d -i 44 | bx hd-private -d -i 5 | bx hd-private -d -i 0 | bx hd-private -i 0 | bx hd-private -i 0 | bx hd-to-ec | sed 's/$/01/' | bx base58check-encode -v 204*

#### XHra5Q1MEtFP7fZhSdx7UCpfNyqa5eeBXzuSU47UXvC8MGAbFxDo

##### 2. BIP 44 synthesis of companion Dash base58check encoded public address using the bitcoin-explorer v3.0 (bx) command line:

*% echo 'This brain wallet is a joke, needs lots of salt and peppering.' | bx base16-encode | bx sha256 | bx hd-new | bx hd-private -d -i 44 | bx hd-private -d -i 5 | bx hd-private -d -i 0 | bx hd-public  -i 0 | bx hd-public  -i 0 | bx hd-to-ec | bx ec-to-address -v 76*

#### XkKCeB63bBiebS4T1jdHUrUH3H2kcQGxW7

Public address above was verified using file:///Users/XXX/JavaScript-Wallets/WalletGenerator/new/WalletGenerator.net/index.html?currency=Dash# from [WalletGenerator](https://github.com/MichaelMure/WalletGenerator.net), and entering the private key synthesized above.

Support for a wallet **sweep** option will be more secure than a **import** option for a private key. 

A nice to have will be the ability to support sweeping an **openly extended BIP 38** encoded Dash paper wallet *(BIP 38 was designed exclusively for Bitcoin)* would be useful, see examples [5A and 5B](https://github.com/libbitcoin/libbitcoin/wiki/Altcoin-Version-Mappings#bx---key-encryption-commands). The ability to shapeshift "sweeps" from other [cryptocurrency](https://github.com/libbitcoin/libbitcoin/wiki/Altcoin-Version-Mappings#bip44-altcoin-version-mapping-table) cold storage paper wallets (WIF encoded or BIP 38 encoded) will also be very useful to capture a greater customer interests.
